### ISSUE TITLE
Tried to use DID and also txref with testnet prefex

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-tx-playground.github.io#15]
It should work if I put in the "Find by TXREF" field if I use the full DID or only txref beginning with x and without the testnet prefix, i.e. both of these should work.

```
did:btcr:xyv2-xzyq-qqm5-tyke
xyv2-xzyq-qqm5-tyke
````

**Comment by kimdhamilton** [comment]
fixed
