### ISSUE TITLE
SatoshiBlockchainSignature2017 details

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-tx-playground.github.io#16]
I would like to see more of the json-ld details that were in the old SatoshiBlockchainSignature2017 signature shown in the signature block, such as blockheight and indxe, etc.

**Comment by kimdhamilton** [comment]
we need to define what those should be. Let's create a BTCR method spec repo and track those there (as opposed to the UI)

**Comment by kimdhamilton** [comment]
done
