### ISSUE TITLE
Not showing DID Description

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-tx-playground.github.io#17]
When I test the txid from my hackathon DID:

```
f8cdaff3ebd9e862ed5885f8975489090595abe1470397f79780ead1c7528107
```

I'm not seeing the url in the op_return

**Comment by kimdhamilton** [comment]
it only shows the final DID description now. We could add helper fields, like links to the tx and op_return, but I don't want to shove too many responsibilities into this page (like we had before), therefore making it harder to grok

**Comment by ChristopherA** [comment]
it wasn't even showing the link, and it wasn't clear that it was loading my old ddo either.

BTW, at some point can you do a pull request on my old DDO to make it conform with yours?

**Comment by kimdhamilton** [comment]
updated
